### PR TITLE
feat: Create a section for User Onboarding and adding Reown

### PR DESCRIPTION
**Pull request by rohit-710**
# Description

This PR creates a "User Onboarding" section under the "Ecosystem" section of ZKsync Era's docs. It also adds Reown as one of the tools available on ZKsync Era for user onboarding. 

## Linked Issues

N/A

## Additional context

N/A

### CODE REVIEW

**Comment by popzxc** [comment]
@rohit-710 thanks for the contribution! Could you please run `bun fix:prettier` and then make sure that `bun ci:check` passes locally?

**Comment by rohit-710** [comment]
Hey @popzxc, the prettier check passes and I made a minor spelling fix as well. However, Cspell tags "Reown" as an unknown word. And I cannot bypass it unless I edit `cspell.json` file. 

So I suppose that you will have to make an exception for that case. Please let me know

**Comment by popzxc** [comment]
@rohit-710 you can add it to the [cspell-blockchain.txt](https://github.com/matter-labs/zksync-docs/blob/main/cspell-config/cspell-blockchain.txt)

**Comment by rohit-710** [comment]
Hey @popzxc, it should be fixed now. Can you take a look?

**Comment by rohit-710** [comment]
Hey @popzxc, just quickly following up here. Can you please take a look now?

**Review by popzxc — APPROVED** [review]
Thanks!

**Pull request merged**
