### PR TITLE
feat: adds envio to zksync supported data indexers

### PR DESCRIPTION
**Pull request by SvenMuller95**
# Description

Adds Envio as a supported Data Indexer and Data Infrastructure Provider for building applications on ZkSync. 

## Linked Issues

N/A

## Additional context

We are also currently working on two community tutorials (one more indexer focused, e.g. indexing factory contracts like liquidity pool pairs and their swaps; and one more data analytics-focused, e.g. fetching all erc20 token transfers on zksync).

### CODE REVIEW

**Comment by itsacoyote** [comment]
@SvenMuller95 Hi! Thanks for the PR, would you mind taking care of the failing lint checks?

For your tutorials, are you aware of the Community Code repo? https://github.com/zkSync-Community-Hub/community-code

**Comment by SvenMuller95** [comment]
Hi @itsacoyote. The one failed lint check is "Envio" as unknown word. The other was trailing spacing which i've resolved. 

Yes we are very aware of the community tutorials, and will be contributing towards these with some indexing and analytics walk-throughs as mentioned in "additional context". thank you!

**Comment by itsacoyote** [comment]
> Hi @itsacoyote. The one failed lint check is "Envio" as unknown word. The other was trailing spacing which i've resolved.
> 
> Yes we are very aware of the community tutorials, and will be contributing towards these with some indexing and analytics walk-throughs as mentioned in "additional context". thank you!

To add the "Envio" word as a valid spelling, you can add it to the entries in https://github.com/matter-labs/zksync-docs/blob/main/cspell-config/cspell-blockchain.txt 
That should make the spelling lint pass 😄 
The markdown linter requires lines to have a max-length, [Line 40](https://github.com/matter-labs/zksync-docs/pull/119/files#diff-9460dbb86967dbf0589cc5af9c04157197c21f6de8b3ae792d324706a7bccc0cR40) just needs to be split into two lines explicitly.

**Comment by SvenMuller95** [comment]
> > Hi @itsacoyote. The one failed lint check is "Envio" as unknown word. The other was trailing spacing which i've resolved.
> > Yes we are very aware of the community tutorials, and will be contributing towards these with some indexing and analytics walk-throughs as mentioned in "additional context". thank you!
> 
> To add the "Envio" word as a valid spelling, you can add it to the entries in https://github.com/matter-labs/zksync-docs/blob/main/cspell-config/cspell-blockchain.txt That should make the spelling lint pass 😄 The markdown linter requires lines to have a max-length, [Line 40](https://github.com/matter-labs/zksync-docs/pull/119/files#diff-9460dbb86967dbf0589cc5af9c04157197c21f6de8b3ae792d324706a7bccc0cR40) just needs to be split into two lines explicitly.

Appreciate the review Sabrina! We should be all good now, lint check passed locally before pushing

**Comment by SvenMuller95** [comment]
@itsacoyote for president

**Review by itsacoyote — APPROVED** [review]

**Pull request merged**
